const mcqData = [
  { q: "ما هو الغرض الرئيسي من CSS؟", opts: ["إضافة وظائف تفاعلية للصفحة", "تنسيق وتجميل عناصر HTML", "ربط قاعدة البيانات بالصفحة", "إنشاء هيكل الصفحة"], ans: 1 },
  { q: "ما هي الطريقة المفضلة لربط CSS بـ HTML؟", opts: ["Inline Style", "Internal Style", "External File", "كلها متساوية"], ans: 2 },
  { q: "أين يُوضع وسم <link> لربط ملف CSS الخارجي؟", opts: ["داخل <body>", "داخل <head>", "داخل <footer>", "في نهاية الصفحة"], ans: 1 },
  { q: "ما هو العيب الرئيسي لطريقة Inline CSS؟", opts: ["لا تعمل في المتصفحات الحديثة", "تحتاج إلى ملف خارجي", "تخلط التنسيق بالمحتوى وصعبة الصيانة", "لا تقبل قيم الألوان"], ans: 2 },
  { q: "كم طبقة يتكون منها Box Model؟", opts: ["2", "3", "4", "5"], ans: 2 },
  { q: "ما الفرق بين padding وmargin؟", opts: ["padding مسافة خارجية، margin مسافة داخلية", "padding مسافة بين المحتوى والحدود، margin مسافة خارجية بين العناصر", "لا فرق بينهما", "padding يُستخدم للألوان فقط"], ans: 1 },
  { q: "ما قيمة الـ Hex للون الأحمر الصافي؟", opts: ["#0000ff", "#00ff00", "#ff0000", "#ffffff"], ans: 2 },
  { q: "ما معنى القيمة الرابعة في rgba(255, 0, 0, 0.5)؟", opts: ["درجة اللون الأحمر", "مستوى الشفافية (Opacity)", "حجم الخط", "سمك الحد"], ans: 1 },
  { q: "ما الخاصية المستخدمة لجعل الصورة تغطي العنصر بالكامل؟", opts: ["background-repeat: no-repeat", "background-size: contain", "background-size: cover", "background-image: full"], ans: 2 },
  { q: "ما الخاصية التي تمنع تكرار الصورة في الخلفية؟", opts: ["background-size: auto", "background-repeat: no-repeat", "background-image: none", "background-color: transparent"], ans: 1 },
  { q: "ما وحدة القياس الشائعة لتحديد حجم الخط؟", opts: ["cm", "mm", "px", "pt"], ans: 2 },
  { q: "ما القيمة التي تجعل الخط مائلاً؟", opts: ["font-weight: bold", "font-style: italic", "text-align: center", "font-size: large"], ans: 1 },
  { q: "ما الخاصية المستخدمة لتوسيط النص أفقياً؟", opts: ["text-align: justify", "text-align: right", "text-align: center", "margin: 0 auto"], ans: 2 },
  { q: "ما الخاصية التي تتحكم في المسافة بين الحروف؟", opts: ["line-height", "letter-spacing", "word-spacing", "font-size"], ans: 1 },
  { q: "ما معنى line-height: 1.5؟", opts: ["ارتفاع السطر 1.5 بيكسل", "المسافة بين الكلمات 1.5", "ارتفاع السطر يساوي 1.5 × حجم الخط الحالي", "عدد الأسطر في الفقرة"], ans: 2 },
  { q: "ما ترتيب طبقات Box Model من الداخل للخارج؟", opts: ["margin → border → padding → content", "content → padding → border → margin", "padding → content → margin → border", "border → content → padding → margin"], ans: 1 },
  { q: "ما الكود الصحيح لتوسيط عنصر أفقياً باستخدام margin؟", opts: ["margin: auto 0", "margin: center", "margin: 0 auto", "margin: 50%"], ans: 2 },
  { q: "أي من التالي يمثل طريقة Internal CSS؟", opts: ["<link rel='stylesheet' href='style.css'>", "<p style='color:red'>", "<style> p { color: blue; } </style> داخل <head>", "@import 'style.css'"], ans: 2 },
  { q: "ما معنى القيمة contain في background-size؟", opts: ["تجعل الصورة تغطي العنصر بالكامل", "تُظهر الصورة كاملة حتى لو فيها مساحات فارغة", "تكرر الصورة", "تخفي الصورة"], ans: 1 },
  { q: "ما قيمة font-weight للخط العادي (غير غامق)؟", opts: ["italic", "bold", "normal", "initial"], ans: 2 },
  { q: "في RGB، ما لون rgb(0, 0, 255)؟", opts: ["أحمر", "أخضر", "أزرق", "أبيض"], ans: 2 },
  { q: "ما الخاصية المستخدمة لتحديد نوع الخط؟", opts: ["font-size", "font-style", "font-family", "font-weight"], ans: 2 },
  { q: "ما الغرض من border-radius؟", opts: ["تحديد سمك الحد", "تدوير زوايا العنصر", "تغيير لون الحد", "إخفاء الحد"], ans: 1 },
  { q: "في أي حالة يُستحسن استخدام Internal CSS؟", opts: ["مشاريع كبيرة متعددة الصفحات", "صفحة واحدة بسيطة أو تجربة سريعة", "عند الحاجة لأعلى أداء", "عند استخدام JavaScript"], ans: 1 },
  { q: "ما وحدة em في CSS؟", opts: ["بيكسل ثابت", "نسبة من حجم الخط الأساسي للعنصر الأب", "نسبة من عرض الشاشة", "نسبة من حجم الخط في جذر HTML"], ans: 1 },
  { q: "ماذا تعني قيمة opacity = 0 في rgba؟", opts: ["اللون كامل وواضح", "نصف شفاف", "شفاف تماماً (غير مرئي)", "لون غامق"], ans: 2 },
  { q: "ما الخاصية المستخدمة لتحديد لون خلفية العنصر؟", opts: ["color", "background-color", "border-color", "text-color"], ans: 1 },
  { q: "ما القيمة الافتراضية لـ background-repeat؟", opts: ["no-repeat", "repeat-x", "repeat (تكرار في كل الاتجاهات)", "repeat-y"], ans: 2 },
  { q: "ما وحدة rem في CSS؟", opts: ["نسبة من حجم الخط الأساسي للعنصر الأب", "نسبة من حجم الخط في جذر HTML", "قيمة بيكسل ثابتة", "نسبة من عرض الشاشة"], ans: 1 },
  { q: "ما الصيغة الصحيحة لتحديد حد بسمك 2px لون أسود؟", opts: ["border: 2px black solid", "border: solid 2px #000", "border: 2px solid #333", "أ أو ج صحيحتان"], ans: 3 }
];

const essayData = [
  { q: "اشرح الفرق بين الطرق الثلاث لربط CSS بـ HTML (External, Internal, Inline) مع ذكر مميزات وعيوب كل طريقة.", marks: 15 },
  { q: "ما هو Box Model في CSS؟ اشرح طبقاته الأربعة بالترتيب مع مثال عملي لكل طبقة.", marks: 15 },
  { q: "اشرح طرق تحديد الألوان في CSS (Named, Hex, RGB, RGBA) مع مثال لكل طريقة.", marks: 15 },
  { q: "ما الفرق بين background-size: cover وbackground-size: contain؟ ومتى تستخدم كل منهما؟", marks: 10 },
  { q: "اشرح خصائص الخط في CSS التالية مع ذكر قيمها الممكنة: font-family, font-size, font-weight, font-style.", marks: 15 },
  { q: "ما الفرق بين padding و margin؟ اكتب مثالاً CSS يوضح كيفية استخدام كل منهما.", marks: 10 },
  { q: "اشرح الفرق بين وحدات px, em, rem في CSS ومتى تُفضّل استخدام كل وحدة؟", marks: 10 },
  { q: "ما خصائص محاذاة النص في CSS؟ اشرح قيم text-align الممكنة مع مثال لكل قيمة.", marks: 10 },
  { q: "اكتب كود CSS كامل لعنصر div يحتوي على: خلفية زرقاء، نص أبيض موسّط، padding داخلي 20px، margin خارجي 10px، وحد بسمك 2px.", marks: 15 },
  { q: "اشرح خاصية line-height وletter-spacing وما تأثيرهما على مظهر النص؟ متى تحتاج لاستخدام كل منهما؟", marks: 10 }
];
